services:
  SakuraFRP-Checkin:
    container_name: SakuraFRP-Checkin
    image: lingyezhixing/sakurafrp-checkin
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - tools-net

networks:
  tools-net:
    external: true
